= Talk Lean: Shorter Meetings, Quick Results, Better Relations
Alan H. Palmer
2013

[abstract]
&#9733; &#9733; &#9734; &#9734; &#9734;

_A simple guide to improve communication_

Alan discusses fundamental and seemingly obvious truths about communication. In practice, people struggle to apply these principles consistently with some bad habits that hinder effective communication. The book provides simple examples like considering one idea at a time, how to start and end meetings, being respectfully direct and realizing what is and is not being communicated, and listening to non-verbal communication like body language. Most people struggle with authentic, active listening and the author clarifies the importance of not just listening, but paying actively seeking to understand.

.Three response approaches are suggested:
1. Respond from the other person's point of view by reflecting something they have said or done with the intent to understand through confirmation and/or clarification
2. Respond from your own point of view using "I" and "me" statements. This approach can be effective by starting with the other person's point of view above and then sharing your personal observations. However, the author challenges well established communication tools of reflection or "reformulation" strategies as empty when they do not directly address your need/want.
3. Respond by combining your perspective with theirs; especially useful in meetings

This book offers broad help, but readers may find satisfaction with books that target more specific communication and collaboration challenges. For example, there are great books that can help you resolve professional and personal conflicts, how to facilitate engaging meetings, and effectively presenting your ideas and concerns to others.
